shellEmulator: true

trustPolicy: no-downgrade
packages:
  - libs/*
  - functions/*
  - rules
  - apps/*
  - scripts

overrides:
  reselect: 5.1.0
onlyBuiltDependencies:
  - "@firebase/util"
  - esbuild
  - msw
  - protobufjs
  - re2
  - sharp
  - unrs-resolver
