minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - "@pnpm/types"
  - semver

shellEmulator: true

packages:
  - libs/*
  - functions/*
  - rules
  - apps/*
  - scripts

overrides:
  reselect: 5.1.0

onlyBuiltDependencies:
  - "@firebase/util"
  - esbuild
  - lefthook
  - msw
  - protobufjs
  - re2
  - sharp
  - unrs-resolver
