steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/video-capture
      - -f
      - functions/video-capture/Dockerfile
      - .
images:
  - gcr.io/$PROJECT_ID/video-capture
