name: 🚀 Deploy to VPS
description: SSH deploy to prod or dev based on branch

inputs:
  environment:
    description: prod or dev
    required: true
  branch:
    description: Branch to pull
    required: true
  vps_host:
    description: VPS host
    required: true
  vps_user:
    description: VPS user
    required: true
  ssh_private_key:
    description: SSH private key
    required: true

runs:
  using: composite
  steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.vps_host }}
        username: ${{ inputs.vps_user }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          export PATH="/home/debian/.nvm/versions/node/v24.14.1/bin:$PATH"
          cd /var/www/${{ inputs.environment }}
          git config pull.rebase false
          git reset --hard origin/${{ inputs.branch }}
          /home/debian/.nvm/versions/node/v24.14.1/bin/pnpm install
          /home/debian/.nvm/versions/node/v24.14.1/bin/pnpm run build:front
          /home/debian/.nvm/versions/node/v24.14.1/bin/pm2 reload ${{ inputs.environment }}
