export const FILTER_MEDIA_TYPE = {
  MOVIES: "MOVIES",
  ADS: "ADS",
  TVSERIES: "TVSERIES",
  DOCUMENTARIES: "DOCUMENTARIES",
  MUSIC_VIDEOS: "MUSIC_VIDEOS",
} as const

export const FILTER_KEY = {
  ANIMATION: "animation",
  MOVIE_TYPES: "movie_types",
  GENRES: "genres",
  YEARS: "years",
  SHOT_TYPES: "shot_types",
  ASPECT_RATIO: "aspect_ratio",
  NUMBER_OF_PERSONS: "number_of_persons",
  BRIGHTNESS: "brightness",
  VIDEO_LENGTH: "video_length",
  VIDEO: "video",
} as const

export const FILTER_NAME = {
  [FILTER_KEY.MOVIE_TYPES]: "Type",
  [FILTER_KEY.GENRES]: "Genre",
  [FILTER_KEY.YEARS]: "Release year",
  [FILTER_KEY.SHOT_TYPES]: "Frame size",
  [FILTER_KEY.ASPECT_RATIO]: "Ratio",
  [FILTER_KEY.NUMBER_OF_PERSONS]: "Characters",
  [FILTER_KEY.BRIGHTNESS]: "Brightness",
  [FILTER_KEY.VIDEO_LENGTH]: "Video length",
  [FILTER_KEY.ANIMATION]: "Animation",
  [FILTER_KEY.VIDEO]: "Video",
} as const

export const FILTER_ANIMATION = {
  ONLY_ANIMATION: "oa",
  WITH_ANIMATION: "wa",
} as const

export const FILTER_GENRES = {
  DRAMA: "DRAMA",
  THRILLER: "THRILLER",
  ACTION: "ACTION",
  ADVENTURE: "ADVENTURE",
  COMEDY: "COMEDY",
  SCI_FI: "SCI-FI",
  CRIME: "CRIME",
  FANTASY: "FANTASY",
  ROMANCE: "ROMANCE",
  MYSTERY: "MYSTERY",
  HORROR: "HORROR",
  BIOGRAPHY: "BIOGRAPHY",
  HISTORY: "HISTORY",
  FAMILY: "FAMILY",
  MUSIC: "MUSIC",
  WAR: "WAR",
  MUSICAL: "MUSICAL",
  SPORT: "SPORT",
  WESTERN: "WESTERN",
  POP: "POP",
  HIP_HOP: "HIP-HOP",
  DOCUMENTARY: "DOCUMENTARY",
  ELECTRONIC: "ELECTRONIC",
  RAP: "RAP",
  ROCK: "ROCK",
  FILM_NOIR: "FILM-NOIR",
  R_AND_B: "R&B",
  ALTERNATIVE: "ALTERNATIVE",
  FASHION: "FASHION",
  INDIE: "INDIE",
  SHORT: "SHORT",
  FUNK: "FUNK",
  SOUL: "SOUL",
  FOLK: "FOLK",
  K_POP: "K-POP",
  POP_ROCK: "POP ROCK",
  ELECTRO_POP: "ELECTRO POP",
  DANCE: "DANCE",
  REGGAE: "REGGAE",
  LATINO: "LATINO",
  JAZZ: "JAZZ",
  COUNTRY: "COUNTRY",
  SOFT_ROCK: "SOFT ROCK",
  AFROBEAT: "AFROBEAT",
  HOUSE: "HOUSE",
  METAL: "METAL",
  WORLDWIDE: "WORLDWIDE",
  DEEP_HOUSE: "DEEP HOUSE",
  DISCO: "DISCO",
  TRAP: "TRAP",
  INSTRUMENTAL: "INSTRUMENTAL",
  JUNGLE: "JUNGLE",
  REGGAETON: "REGGAETON",
  INDIE_ROCK: "INDIE ROCK",
  TECHNO: "TECHNO",
  TRANCE: "TRANCE",
  AMBIENT: "AMBIENT",
  ELECTRONICS: "ELECTRONICS",
  PHONE: "PHONE",
  PUNK: "PUNK",
} as const

export const FILTER_SHOT_TYPES = {
  CLOSE_UP: "Close Up",
  MEDIUM: "Medium",
  MEDIUM_WIDE: "Medium Wide",
  WIDE: "Wide",
  EXTREME_WIDE: "Extreme Wide",
} as const

export const FILTER_RATIO = {
  "1": "1 - square",
  "1_20": "1.20",
  "1_33": "1.33",
  "1_37": "1.37",
  "1_43": "1.43",
  "1_66": "1.66",
  "1_78": "1.78",
  "1_85": "1.85",
  "1_90": "1.90",
  "2_00": "2.00",
  "2_20": "2.20",
  "2_35": "2.35",
  "2_39": "2.39",
  "2_76": "2.76",
  "3_5": "3.5",
  "4": "4",
} as const

export const FILTER_QUERY_PARAMS = {
  movie_types: "mt",
  genres: "g",
  years: "y",
  shot_types: "sht",
  aspect_ratio: "ar",
  number_of_persons: "np",
  only_animation: "oa",
  with_animation: "wa",
  video: "v",
  direction: "dir",
  motion: "mtn",
  video_length: "vl",
  brightness: "b",
} as const
