export const PAGES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SIGNUP: "/signup",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  ADMIN: "/admin",
  LOBBY: "/lobby",
  CAPTURE: "/capture",
  JOIN_LOBBY: "/join-lobby",
  ADMIN_GAMES: "/admin/games",
  ADMIN_SPHERICAL: "/admin/sphericals",
  ADMIN_MAPS: "/admin/maps",
  ADMIN_FLATS: "/admin/flats",
  ADMIN_SUGGESTIONS: "/admin/suggestions",
  ADMIN_USERS: "/admin/users",
  ADMIN_TEST: "/admin/test",
  ADMIN_FULLSCREEN: "/admin/full-screen",
  ADMIN_SPHERICAL_FULLSCREEN: "/admin/spherical-full-screen",
  SEED_MAKER: "/seed-maker",
  MY_SEEDS: "/my-seeds",
  ACCOUNT: "/account",
  PROMO: "/promo",
} as const
