export const PAGES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SIGNUP: "/signup",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  ADMIN: "/admin",
  LOBBY: "/lobby",
  JOIN_LOBBY: "/join-lobby",
  ADMIN_GAMES: "/admin/games",
  ADMIN_SPHERICAL: "/admin/sphericals",
  ADMIN_MAPS: "/admin/maps",
  ADMIN_FLATS: "/admin/flats",
  ADMIN_TEST: "/admin/test",
  ADMIN_FULLSCREEN: "/admin/full-screen",
  ADMIN_SPHERICAL_FULLSCREEN: "/admin/spherical-full-screen",
} as const
