export const PAGES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SIGNUP: "/signup",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  ADMIN: "/admin",
  LOBBY: "/lobby",
  CAPTURE: "/capture",
  JOIN_LOBBY: "/join-lobby",
  ADMIN_GAMES: "/admin/games",
  ADMIN_SPHERICAL: "/admin/sphericals",
  ADMIN_MAPS: "/admin/maps",
  ADMIN_FLATS: "/admin/flats",
  ADMIN_SUGGESTIONS: "/admin/suggestions",
  ADMIN_USERS: "/admin/users",
  ADMIN_TEST: "/admin/test",
  ADMIN_SOCIALS: "/admin/socials",
  ADMIN_SOUNDS: "/admin/sounds",
  ADMIN_LOBBIES: "/admin/lobbies",
  ADMIN_FULLSCREEN: "/admin/full-screen",
  ADMIN_DAILY_CHALLENGE: "/admin/daily-challenge",
  ADMIN_SPHERICAL_FULLSCREEN: "/admin/spherical-full-screen",
  SEED_MAKER: "/seed-maker",
  MY_SEEDS: "/my-seeds",
  ACCOUNT: "/account",
  HISTORY: "/history",
  PROMO: "/promo",
  BLOG: (slug: string) => `/blog/${slug}`,
  DAILY_CHALLENGE: "/daily-challenge",
  DAILY_CHALLENGE_DATE: (date: string) => `/daily-challenge/${date}`,
  RACE: "/race",
  RACE_PLAY: (raceId: string) => `/race/${raceId}`,
  DEATH_RUN: "/death-run",
  DEATH_RUN_PLAY: (deathRunId: string) => `/death-run/${deathRunId}`,
  ADMIN_MARATHON_SEEDS: "/admin/marathon-seeds",
} as const
