import { SOCIALS_STATUS } from "@repo/common"
import { BADGE_VARIANTS } from "@/constants/mapping"

export const SOCIALS_STATUS_TO_BADGE_VARIANT = {
  [SOCIALS_STATUS.ERROR]: BADGE_VARIANTS.RED,
  [SOCIALS_STATUS.DRAFT]: BADGE_VARIANTS.NEUTRAL,
  [SOCIALS_STATUS.WAITING_JOB_START]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.WAITING_CAPTURE]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.IN_PROGRESS_CAPTURE]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.WAITING_AUDIO_EXTRACTION]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.IN_PROGRESS_AUDIO_EXTRACTION]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.WAITING_CUSTOMIZATION]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.IN_PROGRESS_CUSTOMIZATION]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.WAITING_FOR_POST]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.IN_PROGRESS_POSTING]: BADGE_VARIANTS.ORANGE,
  [SOCIALS_STATUS.READY_TO_POST]: BADGE_VARIANTS.GREEN,
  [SOCIALS_STATUS.UPLOADED]: BADGE_VARIANTS.GREEN,
} as const
