import { type MarkerColor } from "@/components/mini-map"

export const SELECTORS = {
  GAME_INPUT_GUESS: "game-input-guess",
  GAME_MAP_GUESS_FORM: "game-map-guess-form",
  MINIMAP: "mini-map-container",
  MAP_SUBMIT: "map-submit",
  NEXT_ROUND_BUTTON: "next-round-button",
  NEXT_ROUND_BUTTON_CONFIRM: "next-round-button-confirm",
  LIVES_CONTAINER: "lives-container",
  SPECIAL_ROUND: "special-round",
  LOBBY_FINISHED: "lobby-finished",
  CHANGE_PSEUDO_MODAL: "change-pseudo-modal",
  CHANGE_PSEUDO_INPUT: "change-pseudo-input",
  CHANGE_PSEUDO_SUBMIT: "change-pseudo-submit",
  GAME_THUMBNAIL_OPTION: (index?: string) => `game-thumbnail-option-${index}`,
  GAME_THUMBNAIL_TITLE: (gameTitle?: string) => `game-thumbnail-${gameTitle}`,
  GAME_MAP: (gameTitle?: string) => `game-map-${gameTitle}`,
  MAP_MARKER: (color?: MarkerColor) => `marker-${color}`,
  MAP_LINE: "marker-line",
  FINISHED_LOBBY_ANONYMOUS_MODAL: "finished-lobby-anonymous-modal",
  DAILY_CHALLENGE_NODE: (date: string, variant: string) =>
    `daily-challenge-node-${date}-${variant}`,
  DAILY_CHALLENGE_BACK: "daily-challenge-back",
  DAILY_CHALLENGE_SPHERICAL: "daily-challenge-spherical",
  DAILY_CHALLENGE_FLAT: "daily-challenge-flat",
  DAILY_CHALLENGE_RESULT_THUMBNAIL: "daily-challenge-result-thumbnail",
  DAILY_CHALLENGE_SHARE_MODAL: "share-daily-challenge-modal",
  DIALOG_CLOSE: "dialog-close",
  STREAK_BADGE: "streak-badge",
  RACE_GUESS_INPUT: "race-guess-input",
  RACE_SCORE: "race-score",
  RACE_TIMER: "race-timer",
  RACE_ROUND_INDEX: "race-round-index",
  RACE_FINISHED: "race-finished",
  RACE_FINISHED_SCORE: (uid: string) => `race-finished-score-${uid}`,
  RACE_FINISHED_ROUNDS: (uid: string) => `race-finished-rounds-${uid}`,
  DEATH_RUN_GUESS_INPUT: "death-run-guess-input",
  DEATH_RUN_SCORE: "death-run-score",
  DEATH_RUN_LIVES: "death-run-lives",
  DEATH_RUN_ROUND_INDEX: "death-run-round-index",
  DEATH_RUN_GIVE_UP: "death-run-give-up",
  DEATH_RUN_FINISHED: "death-run-finished",
  DEATH_RUN_FINISHED_SCORE: (uid: string) => `death-run-finished-score-${uid}`,
  DEATH_RUN_FINISHED_ROUNDS: (uid: string) =>
    `death-run-finished-rounds-${uid}`,
  NAV_JOIN_LOBBY: "nav-join-lobby",
  HOME_JOIN_LOBBY: "home-join-lobby",
  JOIN_LOBBY_CODE_INPUT: "join-lobby-code-input",
  JOIN_LOBBY_FOUND: "join-lobby-found",
  JOIN_LOBBY_NOT_FOUND: "join-lobby-not-found",
  JOIN_LOBBY_SUBMIT: "join-lobby-submit",
  LOBBY_STARTING_STALLED: "lobby-starting-stalled",
  NAV_USER_DROPDOWN_TRIGGER: "nav-user-dropdown-trigger",
  ADMIN_MENU_TRIGGER: "admin-menu-trigger",
  ADMIN_MENU_ACHIEVEMENTS: "admin-menu-achievements",
  ADMIN_ACHIEVEMENT_NEW: "admin-achievement-new",
  ADMIN_ACHIEVEMENT_ROW: (key: string) => `admin-achievement-row-${key}`,
  ACHIEVEMENT_FORM_KEY: "achievement-form-key",
  ACHIEVEMENT_FORM_NAME: "achievement-form-name",
  ACHIEVEMENT_FORM_DESCRIPTION: "achievement-form-description",
  ACHIEVEMENT_FORM_REWARD: "achievement-form-reward",
  ACHIEVEMENT_FORM_GOAL: "achievement-form-goal",
  ACHIEVEMENT_FORM_DIFFICULTY: "achievement-form-difficulty",
  ACHIEVEMENT_FORM_DIFFICULTY_OPTION: (difficulty: string) =>
    `achievement-form-difficulty-option-${difficulty}`,
  ACHIEVEMENT_FORM_SUBMIT: "achievement-form-submit",
  ACHIEVEMENT_FORM_KEY_ERROR: "achievement-form-key-error",
  ACHIEVEMENT_DELETE: "achievement-delete",
  ACHIEVEMENT_DELETE_CONFIRM: "achievement-delete-confirm",
  MAP_FORM_CARD_RARITY: "map-form-card-rarity",
  MAP_FORM_CARD_RARITY_OPTION: (rarity: string) =>
    `map-form-card-rarity-option-${rarity}`,
  MAP_FORM_SUBMIT: "map-form-submit",
  MAP_CARD: (mapId: string) => `map-card-${mapId}`,
  TRADING_CARD: (mapId: string) => `trading-card-${mapId}`,
  PACK_OPEN: "pack-open",
  PACK_STOCK: "pack-stock",
  PACK_TIMER: "pack-timer",
  PACK_REVEAL_CARD: (index: number) => `pack-reveal-card-${index}`,
  PACK_REVEAL_PROGRESS: "pack-reveal-progress",
  PACK_REVEAL_SUMMARY: "pack-reveal-summary",
  PACK_REVEAL_NEW: "pack-reveal-new",
  PACK_OPEN_ANOTHER: "pack-open-another",
  PACK_BACK: "pack-back",
  PACK_SEE_COLLECTION: "pack-see-collection",
  COLLECTION_GAME: (gameId: string) => `collection-game-${gameId}`,
  COLLECTION_GAME_PROGRESS: (gameId: string) =>
    `collection-game-progress-${gameId}`,
  COLLECTION_LOCKED_CARD: (mapId: string) => `collection-locked-card-${mapId}`,
  ADMIN_MAPS_RARITY_FILTER: "admin-maps-rarity-filter",
  ADMIN_MAPS_RARITY_FILTER_OPTION: (filter: string) =>
    `admin-maps-rarity-filter-option-${filter}`,
  NAV_ACHIEVEMENTS: "nav-achievements",
  NAV_PACKS: "nav-packs",
  NAV_COLLECTION: "nav-collection",
  NAV_HISTORY_LINK: "nav-history-link",
  ACHIEVEMENTS_ITEM: (key: string) => `achievements-item-${key}`,
} as const
