import { type MarkerColor } from "@/components/mini-map"

export const SELECTORS = {
  GAME_INPUT_GUESS: "game-input-guess",
  GAME_MAP_GUESS_FORM: "game-map-guess-form",
  MINIMAP: "mini-map-container",
  MAP_SUBMIT: "map-submit",
  NEXT_ROUND_BUTTON: "next-round-button",
  NEXT_ROUND_BUTTON_CONFIRM: "next-round-button-confirm",
  LIVES_CONTAINER: "lives-container",
  SPECIAL_ROUND: "special-round",
  LOBBY_FINISHED: "lobby-finished",
  CHANGE_PSEUDO_MODAL: "change-pseudo-modal",
  GAME_THUMBNAIL_OPTION: (index?: string) => `game-thumbnail-option-${index}`,
  GAME_THUMBNAIL_TITLE: (gameTitle?: string) => `game-thumbnail-${gameTitle}`,
  GAME_MAP: (gameTitle?: string) => `game-map-${gameTitle}`,
  MAP_MARKER: (color?: MarkerColor) => `marker-${color}`,
  MAP_LINE: "marker-line",
  FINISHED_LOBBY_ANONYMOUS_MODAL: "finished-lobby-anonymous-modal",
  DAILY_CHALLENGE_NODE: (date: string, variant: string) => `daily-challenge-node-${date}-${variant}`,
  DAILY_CHALLENGE_BACK: "daily-challenge-back",
  DAILY_CHALLENGE_SPHERICAL: "daily-challenge-spherical",
  DAILY_CHALLENGE_FLAT: "daily-challenge-flat",
  DAILY_CHALLENGE_RESULT_THUMBNAIL: "daily-challenge-result-thumbnail",
  DAILY_CHALLENGE_SHARE_MODAL: "share-daily-challenge-modal",
  DIALOG_CLOSE: "dialog-close",
} as const
