name: 🚀 Deploy {{FUNCTION_NAME}} function

on:
  push:
    paths:
      - .github/workflows/deploy-{{FUNCTION_NAME}}-function.yml
      - functions/{{FUNCTION_FOLDER}}/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    name: ⚙️ Initialize Node.js Environment
    if: github.event_name != 'release'
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

  lint:
    needs: init
    name: 🚨 Lint code
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: 🚨 Lint code
        run: pnpm run lint:ci

  format:
    needs: init
    name: 🎨 Format code
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: 🎨 Format code
        run: pnpm run format

  test:
    runs-on: ubuntu-latest
    needs: init
    name: 🧪 Test
    environment: dev
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: ⚙️ Install Firebase tools
        run: pnpm install -g firebase-tools

      - name: 🔒 Create .env.test file
        run: |
          touch functions/{{FUNCTION_FOLDER}}/.env.test
          echo STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }} >> functions/{{FUNCTION_FOLDER}}/.env.test
          echo DEMO_ENV_VAR='"env test file"' >> functions/{{FUNCTION_FOLDER}}/.env.test

      - name: ✨ Build project
        run: pnpm build --filter=@repo/{{FUNCTION_FOLDER}}

      - name: 🧪 Run tests
        run: firebase emulators:exec --token "$FIREBASE_TOKEN" --project
          "$GCLOUD_PROJECT" 'pnpm test
          --filter=@repo/{{FUNCTION_FOLDER}}'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCLOUD_PROJECT: ${{ secrets.PROJECT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [init, lint, format, test]
    name: 🚀 Deploy {{FUNCTION_NAME}} function
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    environment: prod
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: ⚙️ Install Firebase tools
        run: pnpm install -g firebase-tools

      - name: 🔒 Create .env file
        run: |
          touch functions/{{FUNCTION_FOLDER}}/.env

      - name: 🚀 Deploy to Firebase
        run:
          npx firebase deploy --project "$PROJECT_ID" --only functions:{{FUNCTION_FOLDER}}
          --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
