name: 🚀 Deploy create-party-doc function

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deploy-create-party-doc-function.yml
      - functions/create-party-doc/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    name: ⚙️ Initialize Node.js Environment
    if: github.event_name != 'release'
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

  lint:
    needs: init
    name: 🚨 Lint code
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: 🚨 Lint code
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: init
    name: 🧪 Test
    environment: prod
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: ⚙️ Install Firebase tools
        run: pnpm install -g firebase-tools

      - name: 🔒 Create .env.test file
        run: |
          touch functions/create-party-doc/.env.test
          echo STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }} >> functions/create-party-doc/.env.test
          echo DEMO_ENV_VAR='"env test file"' >> functions/create-party-doc/.env.test

      - name: ✨ Build project
        run: pnpm build --filter=@repo/create-party-doc

      - name: 🧪 Run tests
        run: firebase emulators:exec --token "$FIREBASE_TOKEN" --project
          "$GCLOUD_PROJECT" 'pnpm test
          --filter=@repo/create-party-doc'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCLOUD_PROJECT: ${{ secrets.PROJECT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [init, lint, test]
    name: 🚀 Deploy create-party-doc function
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    environment: prod
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: ⚙️ Install Firebase tools
        run: pnpm install -g firebase-tools

      - name: 🔐 Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 🚀 Deploy to Firebase
        run:
          npx firebase deploy --project "$PROJECT_ID" --only functions:create-party-doc
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
