name: 🚀 Deploy listen-docs 

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deploy-listen-docs-function.yml
      - functions/listen-docs/**
      - libs/schemas/src/firestore/**
      - libs/common/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    name: ⚙️ Initialize Node.js Environment
    if: github.event_name != 'release'
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

  lint:
    needs: init
    name: 🚨 Lint code
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: 🚨 Lint code
        run: pnpm run lint:ci

  format:
    needs: init
    name: 🎨 Format code
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: 🎨 Format code
        run: pnpm run format

  test:
    if: false
    runs-on: ubuntu-latest
    needs: init
    name: 🧪 Test
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: ⚙️ Install Firebase tools
        run: pnpm install -g firebase-tools

      - name: ✨ Build project
        run: pnpm build --filter=@repo/listen-docs

      - name: 🧪 Run tests
        run: firebase emulators:exec --project "$PROJECT_ID" 'pnpm test --filter=@repo/listen-docs'
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [init, lint, format]
    name: 🚀 Deploy listen-docs function
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Initialize Node.js Environment
        uses: ./.github/actions/initialization

      - name: 🔐 Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: ⚙️ Install Firebase tools
        run: pnpm install -g firebase-tools

      - name: 🚀 Deploy to Firebase
        run: npx firebase deploy --project "$PROJECT_ID" --only functions:listen-docs --force
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
